/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows GALAXY-WORLD.glb 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { LaunchStar } from "../launchStar/LaunchStar";
import { Vector3 } from "three";

export function World(props) {
  const { nodes, materials } = useGLTF("/models/world/GALAXY-WORLD.glb");

  return (
    <group {...props} position-y={-1} dispose={null}>
      <group position={[-2, 2, -2.1]} >
        <LaunchStar />
      </group>
      <RigidBody
        colliders="hull"
        type="fixed"
        name="ground"
        userData={{ ground: true }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockEmpty__BlockEmptyMat00.geometry}
          material={materials.BlockEmptyMat00}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockEmpty__BlockEmptyMat00001.geometry}
          material={materials.BlockEmptyMat00}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002.geometry}
          material={nodes.Icosphere002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003.geometry}
          material={nodes.Icosphere003.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01027_1.geometry}
          material={materials.BlockQuestionMat01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01027_2.geometry}
          material={materials.BlockQuestionMat00}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01002_1.geometry}
          material={materials.BlockQuestionMat01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01002_2.geometry}
          material={materials.BlockQuestionMat00}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01003_1.geometry}
          material={materials.BlockQuestionMat01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01003_2.geometry}
          material={materials.BlockQuestionMat00}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01004.geometry}
          material={materials.BlockQuestionMat01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlockQuestion__BlockQuestionMat01004_1.geometry}
          material={materials.BlockQuestionMat00}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/world/GALAXY-WORLD.glb");
