/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows coin.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Coin(props) {
  const { scene } = useGLTF('/models/items/coin.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      {/* <primitive object={nodes.Coin_2} /> */}
      <mesh geometry={nodes.Coin__CoinMat00.geometry} material={materials.CoinMat00} />
    </group>
  )
}

useGLTF.preload('/models/items/coin.glb')
